### ISSUE TITLE
Problem - deployment step

### ISSUE THREAD

**Issue by MaxenceAdnot** [deis/rigger#55]
Hello,

I try to deploy a Deis cluster on Vagrant using Rigger but I'm stuck just after the provisioning:

`Ensuring ssh keys are being served by ssh-agent...
Using released version 1.12.1.
Waiting for etcd/fleet at 127.0.0.1:2222
Timeout waiting for etcd/fleet
Error: failed initializing SSH client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain`

My ssh key is correctly added in the ssh-agent but if I try to connect the host 127.0.0.1:2222 it asks me for a password. If I go to $HOME/.rigger/<hash>/go/src/deis/deis and I type vagrant ssh deis-01 it works...

My vars file : 
`export DEISCTL_TUNNEL="127.0.0.1:2222"
export DEISCTL_UNITS="/Users/maxenceadnot/.rigger/units"
export DEIS_GIT_REPO="https://github.com/deis/deis.git"
export DEIS_GIT_VERSION="1.12.1"
export DEIS_ID="2ba755609c"
export DEIS_ID_DIR="/Users/maxenceadnot/.rigger/2ba755609c"
export DEIS_PROFILE="test-2ba755609c"
export DEIS_ROOT="/Users/maxenceadnot/.rigger/2ba755609c/go/src/github.com/deis/deis"
export DEIS_SOURCE="1"
export DEIS_TEST_AUTH_KEY="mgmt_key.pem"
export DEIS_TEST_AUTH_KEY_FULL="/Users/maxenceadnot/.ssh/mgmt_key.pem"
export DEIS_TEST_DOMAIN="local3.deisapp.com"
export DEIS_TEST_SSH_KEY="/Users/maxenceadnot/.ssh/mgmt_key.pem"
export GOPATH="/Users/maxenceadnot/.rigger/2ba755609c/go"
export ORIGINAL_PATH="/Users/maxenceadnot/.rigger/bins:/Users/maxenceadnot/Development/rigger/bin:/Users/maxenceadnot/.rigger/bins:/usr/local/sbin://Users/maxenceadnot/coreos-k8s-cluster/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/maxenceadnot/Go/bin:/usr/local/opt/go/libexec/bin"
export PATH="/Users/maxenceadnot/.rigger/bins:/Users/maxenceadnot/Development/rigger/bin:/Users/maxenceadnot/.rigger/bins:/Users/maxenceadnot/.rigger/bin:/Users/maxenceadnot/.rigger/2ba755609c/go/bin:/Users/maxenceadnot/.rigger/bins:/Users/maxenceadnot/Development/rigger/bin:/Users/maxenceadnot/.rigger/bins:/usr/local/sbin://Users/maxenceadnot/coreos-k8s-cluster/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/maxenceadnot/Go/bin:/usr/local/opt/go/libexec/bin"
export PROVIDER="vagrant"
export RIGGER_VARS_FILE="/Users/maxenceadnot/.rigger/2ba755609c/vars"
export SSH_AGENT_PID="9726"
export SSH_AUTH_SOCK="/var/folders/48/sfj2z7212q5bkl9_xkzqg0jm0000gn/T//ssh-FjJIlwy5M3pN/agent.9725"
export SUGGEST_DEIS_SSH_KEY="/Users/maxenceadnot/.vagrant.d/insecure_private_key"
export SUGGEST_DEIS_TEST_DOMAIN="local3.deisapp.com"
export VERSION="1.12.1"`

Any idea ?

**Comment by sgoings** [comment]
Hey @MaxenceAdnot - it looks like you're trying to use `DEIS_TEST_SSH_KEY="/Users/maxenceadnot/.ssh/mgmt_key.pem"`

Vagrant sets up the insecure_private_key for you to get access to the machine (see the `SUGGEST_DEIS_SSH_KEY="/Users/maxenceadnot/.vagrant.d/insecure_private_key"` that was shown to you during the configuration phase) which is why the `vagrant ssh` passed but the `Timeout waiting for etcd/fleet` happened.

You should run:

`./rigger configure --provider vagrant`

but choose the suggested `insecure_private_key` when you get to the `DEIS_TEST_SSH_KEY` prompt. Then run:

`./rigger provision`

Let me know how that goes. I'll take a look at making the Deis + Vagrant + Rigger process a bit nicer tomorrow.

**Comment by MaxenceAdnot** [comment]
It works when I use the insecure_private_key. Thank you :+1:
